#django container
version: "2"
services:
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: /app/./celery.sh
    volumes:
      - .:/app
    restart: always
        
      
